### ISSUE TITLE
Criar filtro por times

### ISSUE THREAD

**Issue by Luizefz** [Italo-Fernando/Teapot_project#11]
# Filtro de conteúdo por times - Calendário de jogos
## 👨‍💻 O que fazer?
Cria um componente de filtro por  times para a tela principal do aplicativo.
Ao clicar em um time, o mesmo deve mostrar a seleção, juntamente com adesão de um novo filtro ao clicar no "+". 

## 🔍 Referência

![image](https://github.com/Italo-Fernando/Teapot_project/assets/67990430/c49a4f56-2200-4925-bf0e-0d7b1363da54)

[Link para o Figma](https://www.figma.com/file/xIuCwCdBkjr8EAYkwADy9Z/Pulle?type=design&node-id=0%3A1&mode=design&t=LvBWTg6SsfWBvGir-1)

**Comment by Italo-Fernando** [comment]
Eu quero!!

**Comment by Luizefz** [comment]
Ajustar o conteúdo dos cards como no protótipo. @Italo-Fernando
