### ISSUE TITLE
Cria BottomNavigator

### ISSUE THREAD

**Issue by Luizefz** [Italo-Fernando/Teapot_project#13]
# Criar o BottomNavigator do aplicativo
## 👨‍💻 O que fazer?
Criar a barra que permite passar de uma tela para outra do aplicativo linkando as 3 páginas:
- Jogos
- Canhotos
- Insights

## 🔍 Referência
![image](https://github.com/Italo-Fernando/Teapot_project/assets/67990430/08b5b195-56b9-46b4-b203-0f09675a31aa)

[Link para o Figma](https://www.figma.com/file/xIuCwCdBkjr8EAYkwADy9Z/Pulle?type=design&node-id=0%3A1&mode=design&t=LvBWTg6SsfWBvGir-1)

**Comment by LuisFilipeOliveiraSantos** [comment]
Eu quero
