### ISSUE TITLE
Criar SearchBar canhotos

### ISSUE THREAD

**Issue by Luizefz** [Italo-Fernando/Teapot_project#23]
Barra de pesquisa para pesquisar canhotos
👨‍💻 O que fazer?
Cria um componente de textinput para servir como barra de pesquisa da aba canhotos.
Ao pesquisar um nome, os canhotos devem ser filtrados por esse nome.

- Criar um textinput que devolve uma função OnChange para servir como parâmetro para o filtro.

🔍 Referência

![image](https://github.com/Italo-Fernando/Teapot_project/assets/67990430/2c7ad42f-0e1d-403c-8ac7-5e1046b8b526)

[Link para o Figma](https://www.figma.com/file/xIuCwCdBkjr8EAYkwADy9Z/Pulle?type=design&node-id=0%3A1&mode=design&t=LvBWTg6SsfWBvGir-1)

**Comment by Italo-Fernando** [comment]
fiz um pulll request
