### ISSUE TITLE
Criar AppBar padrão do aplicativo

### ISSUE THREAD

**Issue by Luizefz** [Italo-Fernando/Teapot_project#6]
# Criar AppBar com a logo + texto e o botão de perfil / configurações
## 👨‍💻 O que fazer?
Deve ser realizado após a conclusão da issue #3 -> criar a AppBar que contenha a logo + nome do aplicativo e o botão perfil / configurações. 
Futuramente este botão abrirá um menu popup que mostrará informações**

## 🔍 Referências
![image](https://github.com/Italo-Fernando/Teapot_project/assets/67990430/0a802ac9-ba5d-4487-9015-21631384c169)

[Link para o Figma](https://www.figma.com/file/xIuCwCdBkjr8EAYkwADy9Z/Pulle?type=design&node-id=0%3A1&mode=design&t=LvBWTg6SsfWBvGir-1)

**Comment by LuisFilipeOliveiraSantos** [comment]
Eu quero

**Comment by Italo-Fernando** [comment]
Eu quero!!
